### ISSUE TITLE
We are working sloooooowwwwwwwwlllllllllyyyyyy......

### ISSUE THREAD

**Issue by JJoyce03** [STJRush/Da-Group-of-Legends-2.0#5]
vvvveeeeeerrrrrrryyyyyy ssslllloooooowowwwwwlllllyy

**Comment by AdamIreland** [comment]
This is because you do not kno tha wae of tha master branch, my brudda, take this image it will show u tha wae https://www.google.ie/search?q=ugandan+knuckles&source=lnms&tbm=isch&sa=X&ved=0ahUKEwigjb7Xw8_YAhWB_KQKHZ3KCH8Q_AUICigB&biw=1366&bih=662#imgrc=MqVBpmOHKpU7EM:
